# Generated by Django 4.1.7 on 2023-03-25 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passageiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator(message='email  invalido')])),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereço')),
                ('celular', models.CharField(max_length=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator(message='email  invalido')])),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereço')),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Gênero')),
                ('celular1', models.CharField(max_length=12)),
                ('celular2', models.CharField(blank=True, max_length=12)),
                ('numeroEmer', models.CharField(max_length=12, verbose_name='Numero de Emergência')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companhia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companhia.companhia')),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('distancia', models.CharField(max_length=14, verbose_name='Distância')),
                ('loca', models.CharField(max_length=80, verbose_name='Localização')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.CharField(max_length=15)),
                ('Marca', models.CharField(max_length=30)),
                ('Modelo', models.CharField(max_length=30)),
                ('Cor', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companhia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companhia.companhia')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('partida', models.DateTimeField()),
                ('chegada', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companhia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companhia.companhia')),
                ('motorista', models.ManyToManyField(to='companhia.motorista')),
                ('passageiro', models.ManyToManyField(to='passageiro.passageiro')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companhia.rota')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companhia.viatura')),
            ],
            options={
                'ordering': ['partida'],
            },
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(check=models.Q(('chegada__gt', models.F('partida'))), name='chegada_partida'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_viagem'),
        ),
    ]
